import './globals.css'

import { Merriweather_Sans } from 'next/font/google'

const merriweather_Sans = Merriweather_Sans({
  weight: ['400', '500', '700'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={merriweather_Sans.className}>{children}</body>
    </html>
  )
}
